# Generated by Django 5.2.6 on 2025-10-13 09:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='+996', max_length=12)),
                ('work', models.CharField(max_length=100, verbose_name='На какую должность вы претендуете?')),
                ('skill', models.TextField(verbose_name='Какие навыки у вас имеются?')),
                ('experience_work', models.CharField(max_length=100, verbose_name='Сколько лет/месяцев у вас есть опыт?')),
                ('url_github', models.URLField(verbose_name='Скиньте свою ссылку на GitHub')),
                ('image', models.ImageField(upload_to='', verbose_name='Вставте ваш диплом/сертификат об ококнчании')),
                ('online_offline', models.CharField(max_length=100, verbose_name='Вы хотите работать онлайн или оффлайн?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
