# Generated by Django 5.2.6 on 2025-10-13 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+996', max_length=12)),
                ('work', models.CharField(max_length=100, verbose_name='На какую должность вы претендуете?')),
                ('skill', models.TextField(verbose_name='Какие навыки у вас имеются?')),
                ('experience_work', models.CharField(max_length=100, verbose_name='Сколько лет/месяцев у вас есть опыт?')),
                ('url_github', models.URLField(verbose_name='Скиньте свою ссылку на GitHub')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Вставьте ваш диплом/сертификат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkerUser',
        ),
    ]
