# Generated by Django 5.2.6 on 2025-10-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workerprofile_delete_workeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='user',
        ),
    ]
