# Generated by Django 5.2.6 on 2025-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_workerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Ваш адрес проживания'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='birthday',
            field=models.CharField(max_length=100, null=True, verbose_name='День Рождения'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Введите вашу электронную почту'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone_number',
            field=models.CharField(default='+996', max_length=14),
        ),
    ]
