# Generated by Django 5.2.6 on 2025-10-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workerprofile_address_workerprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Пароль'),
        ),
    ]
