# Generated by Django 5.2.6 on 2025-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workerprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Введите вашу электронную почту'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='Пароль'),
        ),
    ]
