# Generated by Django 5.2.6 on 2025-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_workerprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='ФИО'),
        ),
    ]
