# Generated by Django 5.2.6 on 2025-10-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='напишите название книги')),
                ('description', models.TextField(verbose_name='укажите описание книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите картинку книги')),
                ('quatity_page', models.PositiveIntegerField(blank=True, verbose_name='укажите кол-во страниц')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='укажите автора книги')),
                ('book_audio', models.URLField(verbose_name='укажите ссылку с youtube')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
