# Generated by Django 5.2.6 on 2025-10-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_person_alter_books_options_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'участника', 'verbose_name_plural': 'участники'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'тур', 'verbose_name_plural': 'туры'},
        ),
    ]
