# Generated by Django 5.2.6 on 2025-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_clothe', models.CharField(max_length=100)),
                ('description', models.TextField(default='Одежда нужна для защиты от окружающей среды, например, от холода и жары. Кроме того, она выполняет информационную функцию, сигнализируя о социальном статусе, профессии и индивидуальности человека, а также эстетическую, помогая создавать образ и выражать себя. ')),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='clothes.tag')),
            ],
        ),
    ]
