# Generated by Django 5.2.6 on 2025-10-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='size',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
