# Generated by Django 5.2.6 on 2025-10-21 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('genre', models.CharField(choices=[('Ужасы', 'Ужасы'), ('Фантастика', 'Фантастика'), ('Боевики', 'Боевики'), ('Мелодрама', 'Мелодрама')], default='Фантастика', max_length=50, verbose_name='Жанр')),
                ('date', models.CharField(max_length=50, verbose_name='Дата выхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mark', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='CineBoard.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='films', to='CineBoard.tag', verbose_name='Теги'),
        ),
    ]
