# Generated by Django 5.2.6 on 2025-10-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_alter_person_options_alter_tournament_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Какую книгу вы хотите заказать?')),
                ('description_book', models.TextField(verbose_name='Введите описание книги')),
                ('phone', models.CharField(max_length=100, verbose_name='Укажите ваш номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Введите наш адрес доставки вашего города')),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
        ),
    ]
