# Generated by Django 5.2.6 on 2025-10-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('books', '0004_alter_person_options_alter_tournament_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Basket',
        ),
    ]
